# Generated by Django 5.1.5 on 2025-02-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('origin', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('DOCUMENT', 'Document'), ('BOOK', 'Book'), ('BOARD_GAME', 'Board Game'), ('CLOTHES', 'Clothes'), ('SOUVENIR', 'Souvenir'), ('MEDICINE', 'Medicine'), ('COSMETICS', 'Cosmetics'), ('ELECTRONICS', 'Electronics')], max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('to_remove', models.BooleanField(null=True)),
                ('comment', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('BOX', 'Box'), ('FOLDER', 'Folder'), ('DRAWER', 'Drawer'), ('SHELF', 'Shelf'), ('BAG', 'Bag')], max_length=100)),
                ('slug', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
