# Generated by Django 5.1.5 on 2025-02-02 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.room'),
        ),
        migrations.AddField(
            model_name='inventoryobject',
            name='storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.storage'),
        ),
        migrations.AddField(
            model_name='storage',
            name='furniture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.furniture'),
        ),
    ]
